from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.platypus.tables import Table, TableStyle
from io import BytesIO
from datetime import datetime

def generate_pdf_report(user, input_data, predicted_score, recommendations):

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()
    elements = []

    # Title
    title = Paragraph(
        "<font size=24><b>Student Performance Report</b></font>",
        styles['Title']
    )

    elements.append(title)
    elements.append(Spacer(1, 20))

    # Student Info
    student_info = [
        ["Student Name", user['full_name']],
        ["School", user['school_name']],
        ["Generated On", datetime.now().strftime("%d-%m-%Y %H:%M")]
    ]

    table = Table(student_info, colWidths=[200, 300])

    table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.lightblue),
        ('TEXTCOLOR', (0,0), (-1,-1), colors.black),
        ('GRID', (0,0), (-1,-1), 1, colors.black),
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 10),
    ]))

    elements.append(table)
    elements.append(Spacer(1, 20))

    # Predicted Score
    score_para = Paragraph(
        f"<font size=20><b>Predicted Score: {predicted_score}/100</b></font>",
        styles['Heading2']
    )

    elements.append(score_para)
    elements.append(Spacer(1, 20))

    # Input Data
    input_title = Paragraph(
        "<font size=18><b>Student Inputs</b></font>",
        styles['Heading2']
    )

    elements.append(input_title)
    elements.append(Spacer(1, 10))

    input_rows = [["Factor", "Value"]]

    for key, value in input_data.items():
        input_rows.append([str(key), str(value)])

    input_table = Table(input_rows, colWidths=[250, 250])

    input_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.lightgrey),
        ('GRID', (0,0), (-1,-1), 1, colors.black),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
    ]))

    elements.append(input_table)
    elements.append(Spacer(1, 20))

    # Recommendations
    rec_title = Paragraph(
        "<font size=18><b>Recommendations</b></font>",
        styles['Heading2']
    )

    elements.append(rec_title)
    elements.append(Spacer(1, 10))

    for rec in recommendations:
        p = Paragraph(f"• {rec}", styles['BodyText'])
        elements.append(p)
        elements.append(Spacer(1, 5))

    # Footer
    elements.append(Spacer(1, 30))

    footer = Paragraph(
        "Generated by Student Score Predictor",
        styles['Italic']
    )

    elements.append(footer)

    # Build PDF
    doc.build(elements)

    buffer.seek(0)

    return buffer
